# Usar a imagem oficial do Node.js
FROM node:20-alpine

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o package.json e instalar as dependências
# Isso otimiza o cache do Docker, só reinstalando se o package.json mudar
COPY package*.json ./
RUN npm install

# Copiar o restante do código (será sobreposto pelo volume do docker-compose)
COPY . .

# O comando para iniciar o servidor de desenvolvimento do Vite
# A flag '--host' é crucial para expor o servidor para fora do contêiner
CMD ["npm", "run", "dev", "--", "--host"]
