server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Esta parte serve o seu site (React)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Esta parte (a correção) envia chamadas de API para o backend
    location /api/v1/ {
        # CORREÇÃO: A barra / foi removida do final do proxy_pass
       proxy_pass http://gt-vision-backend:8000;
       
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}