server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Para uma SPA, sempre retorne o index.html para que o roteador do lado do cliente possa assumir.
        try_files $uri $uri/ /index.html;
    }
}