services:
  db:
    image: postgres:13-alpine
    container_name: db-1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  ai-processor:
    container_name: ai-processor-1
    build:
      context: ./ai-processor
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - .env

  frontend:
    container_name: frontend-1
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: