services:
  db:
    image: postgres:13-alpine
    container_name: gt-vision-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - gtv_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: gt-vision-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - gtv_network
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    build: ./backend
    container_name: gt-vision-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - gtv_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ai-processor:
    build: ./ai-processor
    container_name: gt-vision-ai-processor
    volumes:
      - ./ai-processor:/app
    env_file:
      - .env
    # A seção 'environment' com o token JWT foi removida daqui
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - gtv_network
    restart: unless-stopped

  media-server:
    image: bluenviron/mediamtx:latest
    container_name: gt-vision-media-server
    ports:
      - "8554:8554"  # Porta para receber streams RTSP
      - "8888:8888"  # Porta para servir streams HLS (para o navegador)
      - "1935:1935"  # Porta RTMP (opcional)
    environment:
      - MTX_PROTOCOLS=tcp
    networks:
      - gtv_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  gtv_network:
    driver: bridge