"""Adiciona campos de veiculo e imagem a sightings

Revision ID: 1d7135f69bde
Revises: 5aa806a67e79
Create Date: 2025-09-11 14:03:47.534934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d7135f69bde'
down_revision: Union[str, Sequence[str], None] = '5aa806a67e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cameras', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cameras', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('tickets', sa.Column('priority', sa.String(), nullable=True))
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehicle_sightings', sa.Column('vehicle_color', sa.String(), nullable=True))
    op.add_column('vehicle_sightings', sa.Column('vehicle_model', sa.String(), nullable=True))
    op.add_column('vehicle_sightings', sa.Column('image_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_vehicle_sightings_vehicle_color'), 'vehicle_sightings', ['vehicle_color'], unique=False)
    op.create_index(op.f('ix_vehicle_sightings_vehicle_model'), 'vehicle_sightings', ['vehicle_model'], unique=False)
    op.drop_column('vehicle_sightings', 'image_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_sightings', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vehicle_sightings_vehicle_model'), table_name='vehicle_sightings')
    op.drop_index(op.f('ix_vehicle_sightings_vehicle_color'), table_name='vehicle_sightings')
    op.drop_column('vehicle_sightings', 'image_path')
    op.drop_column('vehicle_sightings', 'vehicle_model')
    op.drop_column('vehicle_sightings', 'vehicle_color')
    op.drop_column('users', 'created_at')
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('tickets', 'priority')
    op.alter_column('cameras', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cameras', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cameras', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
