"""add_thumbnail_url_to_camera

Revision ID: 2d0dd8d9d8a7
Revises: 6acb0ea75a87
Create Date: 2025-10-27 17:05:22.910305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0dd8d9d8a7'
down_revision: Union[str, Sequence[str], None] = '6acb0ea75a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'thumbnail_url')
    # ### end Alembic commands ###
