"""Add AuditLog model and integrate into user management

Revision ID: 6acb0ea75a87
Revises: e293324ab514
Create Date: 2025-10-23 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acb0ea75a87'
down_revision: Union[str, Sequence[str], None] = 'e293324ab514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    
    # --- CORREÇÃO APLICADA AQUI ---
    # Passo 1: Adicionar a coluna permitindo nulos temporariamente
    op.add_column('users', sa.Column('password_change_required', sa.Boolean(), nullable=True))
    
    # Passo 2: Definir um valor padrão para as linhas existentes
    # Para usuários existentes, assumimos que eles não precisam trocar a senha.
    op.execute('UPDATE users SET password_change_required = FALSE')
    
    # Passo 3: Alterar a coluna para não permitir mais nulos
    op.alter_column('users', 'password_change_required', nullable=False)
    # --- FIM DA CORREÇÃO ---
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_change_required')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###