"""Add cascade delete from cameras to sightings

Revision ID: a6326182280a
Revises: fe5c5f4cc2d2
Create Date: 2025-09-18 13:34:04.010617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6326182280a'
down_revision: Union[str, Sequence[str], None] = 'fe5c5f4cc2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vehicle_sightings', 'license_plate',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vehicle_sightings', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_vehicle_sightings_vehicle_color'), table_name='vehicle_sightings')
    op.drop_index(op.f('ix_vehicle_sightings_vehicle_model'), table_name='vehicle_sightings')
    op.drop_constraint(op.f('vehicle_sightings_camera_id_fkey'), 'vehicle_sightings', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_sightings', 'cameras', ['camera_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_sightings', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_sightings_camera_id_fkey'), 'vehicle_sightings', 'cameras', ['camera_id'], ['id'])
    op.create_index(op.f('ix_vehicle_sightings_vehicle_model'), 'vehicle_sightings', ['vehicle_model'], unique=False)
    op.create_index(op.f('ix_vehicle_sightings_vehicle_color'), 'vehicle_sightings', ['vehicle_color'], unique=False)
    op.alter_column('vehicle_sightings', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vehicle_sightings', 'license_plate',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
