"""Make camera thumbnail_url nullable

Revision ID: ad0f33cffd45
Revises: 2d0dd8d9d8a7
Create Date: 2025-10-30 14:41:08.714989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0f33cffd45'
down_revision: Union[str, Sequence[str], None] = '2d0dd8d9d8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cameras_client_id_fkey'), 'cameras', type_='foreignkey')
    op.create_foreign_key(None, 'cameras', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_client_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_client_id_fkey'), 'users', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.create_foreign_key(op.f('cameras_client_id_fkey'), 'cameras', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
