"""Initial database schema

Revision ID: c9017181b51a
Revises: 
Create Date: 2025-10-07 18:58:04.553119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9017181b51a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'camera_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('camera_type', postgresql.ENUM('GENERIC_RTSP', 'INTELBRAS_PUSH', name='cameratype'), server_default=sa.text("'GENERIC_RTSP'::cameratype"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
