"""Adiciona lpr_mode na tabela de cameras

Revision ID: fe5c5f4cc2d2
Revises: 1d7135f69bde
Create Date: 2024-05-01 19:33:01.097103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5c5f4cc2d2'
down_revision: Union[str, None] = '1d7135f69bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('lpr_mode', sa.String(), nullable=False, server_default='off'))
    op.create_index(op.f('ix_vehicle_sightings_timestamp'), 'vehicle_sightings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_sightings_timestamp'), table_name='vehicle_sightings')
    op.drop_column('cameras', 'lpr_mode')
    # ### end Alembic commands ###